name: reddit_stonks
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - pip:
      - numpy==1.18.2
      - pandas==1.0.1
      - scikit-learn==0.23.1
      - transformers
      - torch
